# -*- coding: utf-8 -*-
"""ATM Simulator Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZGoH86L01QGYjfb660taUffs4tbV631w
"""

# Define the initial balance
balance = 1000

# Define the PIN
pin = 1234

# Function to display the menu
def display_menu():
    print("ATM Menu:")
    print("1. Check Balance")
    print("2. Withdraw")
    print("3. Deposit")
    print("4. Exit")

# Function to check balance
def check_balance():
    print(f"Your balance is ${balance}")

# Function to withdraw money
def withdraw(amount):
    global balance
    if amount > balance:
        print("Insufficient balance.")
    else:
        balance -= amount
        print(f"Withdrew ${amount}. New balance is ${balance}")

# Function to deposit money
def deposit(amount):
    global balance
    balance += amount
    print(f"Deposited ${amount}. New balance is ${balance}")

# Main program
print("Welcome to the ATM")
entered_pin = int(input("Please enter your PIN: "))

if entered_pin == pin:
    while True:
        display_menu()
        choice = input("Enter your choice: ")

        if choice == '1':
            check_balance()
        elif choice == '2':
            amount = float(input("Enter the amount to withdraw: $"))
            withdraw(amount)
        elif choice == '3':
            amount = float(input("Enter the amount to deposit: $"))
            deposit(amount)
        elif choice == '4':
            print("Thank you for using the ATM. Have a nice day!")
            break
        else:
            print("Invalid choice. Please try again.")
else:
    print("Invalid PIN. Please try again.")

